# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # Elimina espacios o tabs innecesarios al final de las lineas
      - id: trailing-whitespace
      # Elimina terminaciones conflictivas entre Windows y UNIX (CRLF y LF)
      - id: mixed-line-ending
      # Arregla archivos sin una linea nueva final
      - id: end-of-file-fixer
      # Revisa que los archivos de YAML sean válidos
      - id: check-yaml
      # Advierte antes de commitear archivos gigantes
      - id: check-added-large-files
      # Verifica que los archivos de Python tengan una sintaxis válida
      - id: check-ast
      # Verifica que no hayan líneas de un merge incompleto
      - id: check-merge-conflict
    #

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      # Revisa que el código esté en formato Black/PEP-8
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      # Revisa que el código no rompa ninguna regla severa
      # o bien produzca descuentos
      - id: flake8
        args: ["--select", "E9,F63,F7,F82,E501,E22,E23,W191,F403,N"]
        additional_dependencies: [pep8-naming]

  - repo: https://github.com/agucova/check-file-length
    rev: 9f9fb3c59875ae22d908bbb4d4abbfa62f16115b
    hooks:
      # Script personalizado que revisa el criterio de modularización
      # (LOCs <= 400)
      - id: check-file-length
